### ISSUE TITLE
Rename cirAr to circleArea

### ISSUE THREAD

**Issue by braughtg** [Dickinson-COMP-491-492/github-issues-sec1#39]
<a href="https://github.com/braughtg"><img src="https://avatars.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 19:02 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/19_

----

Change the name of the cirAr method to be circleArea to improve readability of the code.

**Comment by thoang43** [comment]
I can make the change to this method.
